### ISSUE TITLE
Add google Analytics

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#1]
Add GA support

**Comment by Vijaykv5** [comment]
@FrancescoXX for adding GA, you'll have to create an account [here](https://analytics.google.com/analytics/web/?authuser=0#/provision/SignUp) and please look onto #21 Description for the setup steps.

**Comment by FrancescoXX** [comment]
thank you @Vijaykv5 , I already have a GA account, I just need to set it up. This was more of a reminder

**Comment by bbbjames** [comment]
i see you've added gtag, i hope you're not setting any cookies until any user accepts them

personally, i go with a zero-cookie policy until someone makes a positive action to accept, then gtag is enabled

have you implemented such a process, privacy policy and compliance?

**Comment by Vijaykv5** [comment]
> i see you've added gtag, i hope you're not setting any cookies until any user accepts them
> 
> personally, i go with a zero-cookie policy until someone makes a positive action to accept, then gtag is enabled
> 
> have you implemented such a process, privacy policy and compliance?

No @bbbjames this won't add any cookies for the user's to accept, also to note that this Enabling of GA has not yet be fixed as you can see there is a build failure in vercel.

**Comment by bbbjames** [comment]
than you @Vijaykv5, good, when we start using it i trust we will have such a mechanism

**Comment by Vijaykv5** [comment]
@FrancescoXX  This PR #30 might fix out Google Analytics issue, because I think we have some unwanted code we already had in during the live stream  that finally led to some conflicts too.
Removal of them would fix the production and addition of GA

**Comment by bbbjames** [comment]
hey @Vijaykv5 i saw @FrancescoXX post its live, were cookie controls and user consent implemented?

**Comment by Vijaykv5** [comment]
> hey @Vijaykv5 i saw @FrancescoXX post its live, were cookie controls and user consent implemented?

Yes!
GA by default  has zero-cookie policy. it only collect user data and send it to GA if the user has granted cookie consent. If a user denies consent, tags will no longer store cookies ( this is by default behaviour of gtag and we don't needa worry on them )

**Comment by bbbjames** [comment]
lets gooo!

**Comment by FrancescoXX** [comment]
it worked, thanks

**Comment by bbbjames** [comment]
i just checked and i see cookies and no user consent

i suggest this is important, but that may just be me, i have a zero-cookie policy until affirmative action by the user

**Comment by FrancescoXX** [comment]
it works correctly #30

**Comment by bbbjames** [comment]
it works, as in GA collects data, but is it compliant?
