### ISSUE TITLE
[FEATURE] Add "DSA" section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#10]
add a section for DSA, and add rust examples

**Comment by prathmesh0125** [comment]
can you tell me this issue in detail

**Comment by shawazi** [comment]
I think he wants a pull request with the implemented feature. So for each issue, we should submit a pull request to help advance that particular solution. 

In this case, I guess we can clone the repo, switch to a dev branch you create, add a page for DSA, create some structure for that page such as data structures section, algorithms section, examples for each, etc.

**Comment by FrancescoXX** [comment]
yes @shawazi m what we need here is just a new component with a list of links.

We will take care of filtering the content later

**Comment by FrancescoXX** [comment]
Add the "DSA in rust" section in the project.

For reference, check these files:
https://github.com/FrancescoXX/rustcrab/blob/main/src/components/DevToolsSection.tsx

This for the data (similar structure)
https://github.com/FrancescoXX/rustcrab/blob/main/src/data/tools.ts

and then insert this component into the page.tsk file (similar to what is here at line 39)
https://github.com/FrancescoXX/rustcrab/blob/main/src/app/page.tsx

**Comment by nikkbh** [comment]
Hi @FrancescoXX, I can work on this feature.
Thanks

**Comment by felixoder** [comment]
> Hi @FrancescoXX, solved that on PR on #69 . Thanks

**Comment by felixoder** [comment]
solved that on PR #69
