### ISSUE TITLE
Create a Fundamental section

### ISSUE THREAD

**Issue by felixoder** [FrancescoXX/rustcrab#104]
It's an idea. We can create a section called fundamentals, give a short explanation and then I can link my videos (I am creating all of them, basically)

you can refer to this playlist

Create a Fundamental Section and give a short explanation about that and redirect to the yt video link of the respective topic.

The references - https://www.youtube.com/watch?v=R33h77nrMqc&list=PLPoSdR46FgI412aItyJhj2bF66cudB6Qs

**Comment by FrancescoXX** [comment]
the section should be called "Fundamentals" or "Key Concepts"

**Comment by saivinaygondrala** [comment]
if no one is working on it i can work on it @FrancescoXX assign it to me

**Comment by felixoder** [comment]
After creation of lessons may be this section seems unimportant ss lessons has all comp about rust.
