### ISSUE TITLE
[BUG] Footer : Copyright is not visible in Light Mode.

### ISSUE THREAD

**Issue by ranjanport** [FrancescoXX/rustcrab#113]
The copyright text in the footer is not visible when switched from Dark mode to light mode, and hence required workaround.

**Expected Behavior**

Copyright Text to become Dark when Light mode is switched.

**Actual Behavior**

Not shown as the color is set to White.

**Screenshots (if applicable)**

![image](https://github.com/user-attachments/assets/c6ee8eca-14a9-4702-953f-850c7a1005d0)

**Comment by FrancescoXX** [comment]
closed by #114
