### ISSUE TITLE
Navigation bug

### ISSUE THREAD

**Issue by felixoder** [FrancescoXX/rustcrab#115]
after navigating to the see more func the nav menus are not working 

https://github.com/user-attachments/assets/4c75b343-92b0-42eb-bd8b-d4fbd1e5cb1e

**Comment by Thebeast01** [comment]
I did try to solve it but, I don't know whether it is good practice or not, I just added '/' in front of # in the nav links 
Although It worked but I think is not the best way to do it, 
So, Is there any other way ?

**Comment by felixoder** [comment]
yes that is the way to solve that bug did you raise the PR ? actually I am working with a functionality of #104 may that cause a conflicts.

**Comment by Thebeast01** [comment]
No, I haven't raised the pr yet

**Comment by felixoder** [comment]
ok then

**Comment by Thebeast01** [comment]
Since you are working on the fundamental section so you will also add it to the navigation menu right? 
So you add a forward slash to links as well.
 Do you think that's all right?

**Comment by devvsakib** [comment]
Yes, adding / before # will fix it. Thanks

**Comment by felixoder** [comment]
@Thebeast01  yes I will add that fs

**Comment by FrancescoXX** [comment]
@Thebeast01 want to be assigned to that?

**Comment by Thebeast01** [comment]
@FrancescoXX No @felixoder  Is working on it, its just a small fix

**Comment by FrancescoXX** [comment]
assigned to @felixoder .

If you want a better place to talka bout the project, we can use a channel on my discord server

**Comment by felixoder** [comment]
yeah for sure. @FrancescoXX

**Comment by felixoder** [comment]
@devvsakib @Thebeast01 One thing to mention if you use '/' navigation as we are using next file based routing so we will navigate to the more option page as that are (eg, books/page.tsx) 

but this is an SPA (single page application) so for eg, /devtools we should navigate to # home menu.

if you use / instead # you can get this error

https://github.com/user-attachments/assets/11d6326b-50fd-4432-98c0-c54d859262dc

I am working with this if you wanna discuss you can (may be we can get some easy option)

**Comment by devvsakib** [comment]
@felixoder  No, its because the folder name is different. please check again. 
see  there are devtools folder, but link is dev_tools.

**Comment by devvsakib** [comment]
and there are no folder call projects, raise an issue and work on it☘️

**Comment by felixoder** [comment]
That's not the problem [though there is a spell mistake] buddy either you have to create a separate people folder and a projects folder .
But still I want instead going to / route it should stay in main page while navigating to nav menu. I hope you got it.

I dont want this to be a multi page app while navigating to other menu. 
 

https://github.com/user-attachments/assets/0502f107-75ee-4ba5-9365-00673a139d3b

**Comment by felixoder** [comment]
@devvsakib I want this to be a SPA so may be we will find some solution to make it SPA.

**Comment by devvsakib** [comment]
did @FrancescoXX told you to make it SPA?

**Comment by felixoder** [comment]
@FrancescoXX  are you good with SPA or we will make it multi page navigation app ? do you have problem with that?

**Comment by felixoder** [comment]
@devvsakib That's why I have discussed it here! so that we will discuss that it will remain a SPA or a multi page route

**Comment by Thebeast01** [comment]
@felixoder 
No, I didn't say use / instead of # 
I said Use both 😂😂, That why I was not sure that, it is a good practice or not, 
Like locally If I'm writing link like this /#books, 
Then it is working

**Comment by felixoder** [comment]
@Thebeast01 Yeah! I have tried tons of fixes of fix but I found this /# is best! if anyone get another may be they raise some PR

**Comment by devvsakib** [comment]
Logically, we don't need to add an id in the menu. We can directly navigate the user to the dev tool/book etc. pages when the user clicks on the menu. That makes sense!

**Comment by felixoder** [comment]
Make sence but go to my pr I've fixed that

**Comment by Thebeast01** [comment]
@devvsakib  but then will it scroll smoothly as it is now?

**Comment by felixoder** [comment]
Yeah
