### ISSUE TITLE
Improve the Readme file

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#12]

**Comment by Sophyia7** [comment]
@FrancescoXX what changes are you looking to improve on the Readme?

**Comment by FrancescoXX** [comment]
@Sophyia7 add more details about the project and the resources we will include

have details about the stack
update the features (we are integrating Google analytics, for example)

**Comment by FrancescoXX** [comment]
@Sophyia7 let me know if you want to work on this, just a few addition might be nice

**Comment by Sophyia7** [comment]
Yes, i want to work on this

**Comment by FrancescoXX** [comment]
great. btw I am live on the discord server, if you want to join

**Comment by FrancescoXX** [comment]
@Sophyia7 , when ou want to take a look, I can give you a list of the things we implementd (too many so far!
)

**Comment by Sophyia7** [comment]
@FrancescoXX please share the list. I will work on this issue today.

**Comment by FrancescoXX** [comment]
hey @Sophyia7 , you cna check the closed issues 

https://github.com/FrancescoXX/rustcrab/pulls?q=is%3Apr+is%3Aclosed

quick recap, a part what you just see:
- created section template
- created card template
- added books section
- added projects section
- added devtools section
- custom substack email form
- repository setup (Pr, bug,  issue templates, licenses )
- footer with social icons for 6 social media
- added a simple cookie consent prompt
- added google analytics implementation
- added Docekr support
- added daily dev integration (Rust developers squad)


mm, that's it for now...it's a ot of stuff

We definitively need to create a versioning system with changelog.

You can say that now we are at version 0.2.0
