### ISSUE TITLE
[FEATURE] create a component for Search functionality instead using same code for all page/section

### ISSUE THREAD

**Issue by devvsakib** [FrancescoXX/rustcrab#125]
**Description**

Create a component for a search filter. It should be reusable for every page.

**Comment by devvsakib** [comment]
I will work on it. Assign me please

**Comment by Juhaszky** [comment]
Dear @FrancescoXX !
I would like to work on this issue. I was not able to assign it to myself.
Could you help me with that?
Best regards,
Juhaszky

**Comment by FrancescoXX** [comment]
hey @devvsakib , I am assigning this to you while live lol

**Comment by devvsakib** [comment]
@FrancescoXX  Just turned off my pc few min ago👀

**Comment by FrancescoXX** [comment]
@devvsakib do you still want to work on this?

**Comment by timmy471** [comment]
@FrancescoXX, I would like to work in this if its still available. Please assign to me

**Comment by timmy471** [comment]
@FrancescoXX

**Comment by devvsakib** [comment]
@timmy471 you can work on this

**Comment by FrancescoXX** [comment]
done @timmy471
