### ISSUE TITLE
[OTHER] Improve Navbar UI for mobile device

### ISSUE THREAD

**Issue by devvsakib** [FrancescoXX/rustcrab#127]
**Description**
Improve the mobile navbar by using 100vw 100vh for better visibility and user experience.

**Expected Behavior**

The mobile menu should open in full screen.

**Actual Behavior**
now it only shows a piece of block

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/6fc35700-75d6-498a-a4b3-cf3ca435587f)

**Comment by saivinaygondrala** [comment]
Assign it to me ill work on it @devvsakib

**Comment by FrancescoXX** [comment]
hay @saivinaygondrala do you still want to work on this?

**Comment by saivinaygondrala** [comment]
I can work on it. Assign it to me @FrancescoXX .

**Comment by saivinaygondrala** [comment]
This was resolved in PR #130 @FrancescoXX

**Comment by FrancescoXX** [comment]
we are keeping this for now
