### ISSUE TITLE
[BUG] Navigation issue in Mobile 

### ISSUE THREAD

**Issue by saivinaygondrala** [FrancescoXX/rustcrab#131]
**Description**

Unable to navigate to DSA and Lessons from the Navbar Mobile. 

**Screenshots **
![WhatsAppVideo2024-07-17at19 31 13_cd4dfdd9-ezgif com-resize](https://github.com/user-attachments/assets/f661f8c6-c36d-45af-951d-442ce4cb790f)

**Comment by dvpavan-kumar** [comment]
im working on it

**Comment by tusharkaran** [comment]
@saivinaygondrala @dvpavan-kumar is this fixed ?

**Comment by dvpavan-kumar** [comment]
> @saivinaygondrala @dvpavan-kumar is this fixed ?

Yes fixed

**Comment by saivinaygondrala** [comment]
This issue can be closed
