### ISSUE TITLE
Navigation Issue on mobile (Related to routes and sections)

### ISSUE THREAD

**Issue by shibu69** [FrancescoXX/rustcrab#136]
**Description**

When you are on mobile and on home if you click on any button like books , DSA, developer tools or other then you will be redirected to that particular route. But from there if you click on any other menu items in navbar it is redirecting to sections on that particular route.

**Expected Behavior**

It should go to that particular route not on the section.

**Video**
[screen-capture (1).webm](https://github.com/user-attachments/assets/52345f7b-a5bf-4a14-a67e-355c1245e039)

**Comment by saivinaygondrala** [comment]
I can work on it.

**Comment by FrancescoXX** [comment]
good luck @saivinaygondrala

**Comment by saivinaygondrala** [comment]
I can see everything working as expected.


https://github.com/user-attachments/assets/a6b45e2e-9e5b-4697-a2df-b64b9a898d27

**Comment by shibu69** [comment]
Yes , It is working as expected.

**Comment by saivinaygondrala** [comment]
> Yes , It is working as expected.

So this issue can be closed
