### ISSUE TITLE
Books and Dev Tools Headings 

### ISSUE THREAD

**Issue by leetebbs** [FrancescoXX/rustcrab#138]
**Description**

Books and Dev Tools headings are not in the same position as the rest of the headings

**Expected Behavior**

Should be :

![New_books](https://github.com/user-attachments/assets/917e311d-cccd-4b65-854c-dc4a852d238d)

**Actual Behavior**

![heading_books](https://github.com/user-attachments/assets/0083097f-0fb4-4410-94f5-aedd3c75f506)

Solved @ https://github.com/FrancescoXX/rustcrab/pull/137

**Comment by devvsakib** [comment]
Close this issue @leetebbs
