### ISSUE TITLE
The people section looks too clumsy

### ISSUE THREAD

**Issue by felixoder** [FrancescoXX/rustcrab#148]
https://github.com/user-attachments/assets/64196353-fedd-48fd-ba96-cb4439c23b02

As you can see for the small devices it looks decent but may be for large and medium devices it is looking like very tiny

**Comment by tusharkaran** [comment]
is this fixed ?
Can i work on this ?

**Comment by FrancescoXX** [comment]
yes

**Comment by tusharkaran** [comment]
do you have any design , how should i implement any larger device ?
any idea can you suggest me for the design ?

**Comment by felixoder** [comment]
Just see that in a larger device the content takes some grid view (eg, 2 comp in a grid-col) but here the width is too tiny of the people content.
ref: 

https://github.com/user-attachments/assets/502523d7-8996-4abe-ab56-51bf64deb571

you can fix the grid layout to fix this.

The main thing is you have to increase the width of the comp 

[and also make sure that when there will be multiple person it will not damage the responsiveness]

*you can manually add some demo people to fix that

**Comment by tusharkaran** [comment]
got it . will fix this

**Comment by tusharkaran** [comment]
[screen-capture.webm](https://github.com/user-attachments/assets/ec2a040b-750f-46ab-bd0a-ec099f383b8f)

does this look good , if it is ohk , will create pull request  .

**Comment by tusharkaran** [comment]
shall i create pull request ?

**Comment by FrancescoXX** [comment]
we are remiving the people section for now, but thanks
