### ISSUE TITLE
[BUG] Youtube thumbnails overflowing at certain Dimensions of the Screen

### ISSUE THREAD

**Issue by saivinaygondrala** [FrancescoXX/rustcrab#149]
**Description**

At certain dimensions the Youtube thumbnails were overflowing and looks bit inconsistent.

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/ed0c1b72-6cbd-4f16-a8ce-03fef740d865)

Add screenshots or other media to help explain the issue.

**How to fix**
 
This can be fixed by making the background size contain.

**Comment by akkota** [comment]
Would love to work on this, I have experience with Tailwind CSS.

**Comment by FrancescoXX** [comment]
Hey @akkota , let me know in case you don't want to work on this anymore

**Comment by saivinaygondrala** [comment]
https://github.com/FrancescoXX/rustcrab/pull/159
This is good to merge @FrancescoXX .
