### ISSUE TITLE
Navbar and Components Overflow Issue on Small Screens (360px and Below)

### ISSUE THREAD

**Issue by bilelBoulhia** [FrancescoXX/rustcrab#151]
**Description**

the wbsite lack responsiveness specially on small screens. The navbar and youtube thumbnails overflows  and the book covers are too small which is causing layout and readability issues  and extra space on the right side of the screen. 

**Expected Behavior**

 website  layout  should adjust dynamically depending on the screen resolution ( down to 320px )

**Screenshots (if applicable)**

![Untitleasdasdasdd](https://github.com/user-attachments/assets/442bcaa7-afe1-4933-bfe8-9051910d0495)

![Unasdasdtitled](https://github.com/user-attachments/assets/ea156bd9-bcb7-4360-85dc-2291460ce8a0)

**Comment by bilelBoulhia** [comment]
ps : im working on this issue , since i can't  assign it to myself

**Comment by prathmesh0125** [comment]
i can do this @FrancescoXX  can you please assign this task to me
