### ISSUE TITLE
Update the newsletter number from 2400 to 2600

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#154]
UIpdate the number from 2400 to 2600

![image](https://github.com/user-attachments/assets/4b330441-84a2-487c-9592-28d9db54cf5b)

**Comment by prathmesh0125** [comment]
ok i do this @FrancescoXX

**Comment by prathmesh0125** [comment]
i did this @FrancescoXX  
![Uploading Screenshot (212).png…]()

**Comment by prathmesh0125** [comment]
i did this @FrancescoXX  
![Screenshot (212)](https://github.com/user-attachments/assets/752f8b91-8203-466e-b00e-cfd3a8fe2712)

**Comment by FrancescoXX** [comment]
thanks
