### ISSUE TITLE
Navbar Styling Issue on Homepage on meduim size (640 to 760)

### ISSUE THREAD

**Issue by prathmesh0125** [FrancescoXX/rustcrab#157]
**Description**
The navbar on the homepage doesn't look visually appealing for the medium size like . The alignment and spacing seem off, especially when viewed on different screen sizes. This issue is noticeable in the attached screenshot.

![navbar](https://github.com/user-attachments/assets/b228c36c-d1aa-4c1b-9fc1-5ce82e8710d5)

Steps to Reproduce:

Visit the Rustcrab homepage.
Observe the navbar's alignment and spacing on a medium-sized screen (640 t0 760px width).

Expected Behavior:

The navbar should have consistent spacing and alignment across all screen sizes.
The text should be centered vertically, and the spacing between menu items should be even.

**Comment by prathmesh0125** [comment]
@FrancescoXX  can i work on this

**Comment by FrancescoXX** [comment]
hey @prathmesh0125 , @TukhtayevaRoziya already raised a PR. I can assign this to them or you can work on it.

#158

**Comment by prathmesh0125** [comment]
ok you can assign them , they already fixed it
