### ISSUE TITLE
[FIX] Changes in the md view of card in the dev tools section 

### ISSUE THREAD

**Issue by Aditya-NV-06** [FrancescoXX/rustcrab#160]
Description
   Major change
         I encountered a design issue in the dev tools components section.
        This happens when it reaches the condition min width - 768px.
  Minor change
         Anchor tags in the footer section should be changed to the Link for page optimizing stuff.
         Li tags should be placed in the Navbar section.

**Expected Behavior**

![Screenshot (70)](https://github.com/user-attachments/assets/cda0d2bc-09ff-480a-8ea6-13e946c14310)

**Actual Behavior**
![Screenshot (69)](https://github.com/user-attachments/assets/34d34539-2732-4014-81fb-4a8c3b6af987)

I have added pr for this respective issue

**Comment by ironcrush2006** [comment]
For this issue the corresponding pr for this fix is fix: minor layout and link issues #161
