### ISSUE TITLE
Add a Responsive Navbar

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#20]
Add a simple navbar at the top that collapses in a burger menu for mobile

Add these categories for now:
- courses
- books
- resources
- projects
- dev tools
- people
- events

**Comment by Thebeast01** [comment]
This navbar should be on the first page right, where, it is asking for the user's email to subscribe.

**Comment by Thebeast01** [comment]
I would like to work on this issue

**Comment by Thebeast01** [comment]
I have created the navbar, 
I'm attaching a few Images If you approve it then I'll create a pull request
![Screenshot 2024-07-13 095218](https://github.com/user-attachments/assets/5c534eee-785f-47f2-9f4b-ce4cd001fc11)
![Screenshot 2024-07-13 095245](https://github.com/user-attachments/assets/da003254-5b26-415e-87f8-e17da588a298)
![Screenshot 2024-07-13 095256](https://github.com/user-attachments/assets/db7a71b2-8fe1-40f6-b8c7-7319d699b558)

**Comment by Thebeast01** [comment]
@FrancescoXX sir please check it out

**Comment by FrancescoXX** [comment]
we had 2 people working on this before it being assigned. PLease  request to be assigned, in the meanwhile I will check both of the PRs

**Comment by iharsh02** [comment]
@FrancescoXX can you assign the issue to me , if you want any changes please tell

**Comment by Thebeast01** [comment]
@FrancescoXX  can you assign this to me
