### ISSUE TITLE
[FEATURE] Add GitHub Action to check for linting

### ISSUE THREAD

**Issue by Pradumnasaraf** [FrancescoXX/rustcrab#24]
**Description**

Automate the process to check PR errors and Linting with the help of GitHub Action.

**Comment by prathmesh0125** [comment]
ca i do like continues integration

**Comment by FrancescoXX** [comment]
I will check this @prathmesh0125 , ty

**Comment by FrancescoXX** [comment]
@DhairyaMajmudar , I merged but it's really slowing down the process of merging, it takes 5-10 minutes every time. any way to make it quicker or remove some parts? IT sems an overhead in this phase of the project

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar , I merged but it's really slowing down the process of merging, it takes 5-10 minutes every time. any way to make it quicker or remove some parts? IT sems an overhead in this phase of the project

I see this might be happening due to post caching part lemme remove it from the workflow
