### ISSUE TITLE
[FEATURE] Add Docker and Compose support 

### ISSUE THREAD

**Issue by Pradumnasaraf** [FrancescoXX/rustcrab#25]
**Description**

Dockerize the repo and also add compose support for the local development.

**Comment by FrancescoXX** [comment]
maybe we just need the local dev. Do we really need it for a next js project?

**Comment by Pradumnasaraf** [comment]
> maybe we just need the local dev. Do we really need it for a next js project?

Yes, I think so. It will help people who are not familiar Next.js to contribute.

**Comment by FrancescoXX** [comment]
great, do you want to be assigned to this? @Pradumnasaraf

**Comment by shravankumar8** [comment]
cool ! fran assign this to  me
i can start working on this

**Comment by shravankumar8** [comment]
@FrancescoXX

**Comment by FrancescoXX** [comment]
great

**Comment by FrancescoXX** [comment]
#27
