### ISSUE TITLE
Add sections

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#3]
We need to add new sections:

- courses
- books
- dev tools
- relevant people in the rust ecosystem

Each of the sections should have a dedicated page and 

for the easy updates, we can create a JSON file and read it in the specific component.

We still need the logic for this

**Comment by Vijaykv5** [comment]
@FrancescoXX How are we trying to have these sections?
does it can be styled like cards in the homepage or have them in navbar that would link them to separate page?

**Comment by FrancescoXX** [comment]
for now I'd like to have a simple navbar. do you want to create an issue and work on a simple dummy navbar? @Vijaykv5

**Comment by Vijaykv5** [comment]
Cool.
I'll just add a draft PR

**Comment by FrancescoXX** [comment]
nice, let's keep it supersimple for now, just some cards and maybe the logic of how these templates might work (maybe fetching a local json in a folder

**Comment by FrancescoXX** [comment]
@Vijaykv5 we have a temp section for dev tools already and I think it's well written

So for now let's close this And let's create ne issues

**Comment by Vijaykv5** [comment]
Sure @FrancescoXX
