### ISSUE TITLE
[BUG] Substack Embed isn't Responsive on Home page

### ISSUE THREAD

**Issue by soham901** [FrancescoXX/rustcrab#32]
**Description**
The Substack embed on the homepage is not responsive, meaning it does not adjust its size and layout appropriately when viewed on different screen sizes or devices. This issue causes layout problems and makes the content less accessible to users on mobile or tablet devices.

**Expected Behavior**
The Substack embed should resize itself to fit within the viewport of any device, maintaining readability and usability. This would involve adjusting its width, height, and possibly rearranging its contents to ensure it looks good on all screen sizes.

**Actual Behavior**
Instead of being responsive, the Substack embed retains its original dimensions, causing it to overflow within its container. This results in awkward layouts, such as horizontal scroll bars appearing, content being cut off, or excessive white space around the embed.

**Screenshots (if applicable)**
![screenshot-2024-07-13-09-23-26](https://github.com/user-attachments/assets/478f56e2-0269-4beb-ac11-4b04dec65e32)

**Additional Information**
- This problem occurs in Chrome on Android.
- Any recent changes to the homepage that might be relevant (e.g., CSS updates, new JavaScript libraries, etc.).

**Comment by FrancescoXX** [comment]
hey @soham901 , this is because the embedded form they provided is not modifable. the solution would be to use a substack custom form, do you want to look for a solution?
