### ISSUE TITLE
Use Simple Analytics in place of GA

### ISSUE THREAD

**Issue by Astrodevil** [FrancescoXX/rustcrab#39]
Google Analytics collects a lot of unnecessary data that are not required for small projects. Instead, try using a simpler analytics tool like [Umami](https://umami.is/). It also has a public page feature, allowing you to easily share analytics with others.

Simple for you, good for site visiters.

**Comment by FrancescoXX** [comment]
I never used this. I am open to discussions, but at least we have something working for now.

**Comment by dansholds** [comment]
Umami is a simple one-liner in your head and most importantly:

<img width="717" alt="Screenshot 2024-07-13 at 13 16 08" src="https://github.com/user-attachments/assets/3a0e47cf-c7d3-40dc-a460-7782932667cf">

I'm not sure Google abide by the same rules?

**Comment by FrancescoXX** [comment]
good points @dansholds . I am not familiar with it. How long would it take to set it up and what's needed on my end?

**Comment by dansholds** [comment]
> good points @dansholds . I am not familiar with it. How long would it take to set it up and what's needed on my end?

You can add it here, in place of the Google implementation - https://github.com/FrancescoXX/rustcrab/blob/b92495782c100fb09b3d3499d3031bb6f008c811/src/app/layout.tsx#L20

Just log in to https://umami.is , Click "add website" grab the code, and add it to the head.

The site mentioned installation but that's not required 🤙 

(I would submit a PR but it needs you to grab the umami code)

**Comment by dansholds** [comment]
> I would say, less than 5 minutes.
> 
>     * Signup
> 
>     * Add Site domain
> 
>     * Copy tracking script and paste in your ... section of main file
> 
>     * All set, enjoy simple analytics

+1

I was genuinely surprised how fast I had a accurate analytics dashboard up and running!

**Comment by soham901** [comment]
@FrancescoXX , I am using Umami in my recent freelance project. It's very easy, fast, and cheap, and you can create custom reports as well. You should try it once.

**Comment by FrancescoXX** [comment]
we are not changing the analytics for now
