### ISSUE TITLE
Move the dev tools section out of the main page

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#42]
We have sometihng to start with in terms of section, but it's on the main page.

Move those 3 buttons to a separate component 

we will link this to a button on the navbar later

![image](https://github.com/user-attachments/assets/a8693a1e-108f-4b11-930b-d22ee786aff3)

**Comment by saivinaygondrala** [comment]
Hey @FrancescoXX do you mean to move those Rspack and Zed IDE , Helix Editor into navbar?

**Comment by FrancescoXX** [comment]
it's fixed now @saivinaygondrala . next step is to improve this section

**Comment by saivinaygondrala** [comment]
Can i know something in detail about which section is to be improved @FrancescoXX

**Comment by saivinaygondrala** [comment]
So that ill work on that

**Comment by FrancescoXX** [comment]
great. do you want to work on the component or collecting projects?

**Comment by saivinaygondrala** [comment]
ill work on components
