### ISSUE TITLE
ADD Cookie-control and consent for users

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#46]
ADD Cookie and consent for users

a simple, functional banner works for now

**Comment by devvsakib** [comment]
Let me work on this issue @FrancescoXX 👋

**Comment by Piyush-Kumar-Ghosh** [comment]
Hi @FrancescoXX ,

I wanted to let you know that I've completed the implementation of the cookie consent banner. 
Could you please review it and let me know your thoughts?

**Comment by FrancescoXX** [comment]
assigned this to @devvsakib , he asked for this first

@Piyush-Kumar-Ghosh thanks for your PR, but pelase don't work on something before you get assigned to it

**Comment by G0HAN3** [comment]
Hey @FrancescoXX  can u assign me this issue.

**Comment by FrancescoXX** [comment]
@G0HAN3 it's already done. heck it and prepose changes if you want to make an improved version
