### ISSUE TITLE
[FEATURE] Add Shadcn UI Support

### ISSUE THREAD

**Issue by soham901** [FrancescoXX/rustcrab#48]
**Description**

We aim to integrate Shadcn UI into our project to enhance the UI components with a modern and consistent design. This will involve setting up Shadcn UI and refactoring existing components to use Shadcn UI where applicable.

**Expected Behavior**

- Shadcn UI should be installed and configured correctly within the project.
- Existing UI components should be refactored to use Shadcn UI components where appropriate.
- The overall design should be consistent and improved, leveraging Shadcn UI's features.
- Dark and light mode compatibility should be maintained.

**Actual Behavior**

Currently, we are using plain Tailwind CSS, which requires additional classes and dark mode classes in each component, resulting in a lot of redundant code. This issue can be addressed by integrating Shadcn UI.

**Additional Information**

- Ensure that the integration does not break any existing functionalities.
- Update documentation to reflect the usage of Shadcn UI components.
- Conduct thorough testing to verify that all refactored components work as expected.
- Provide a style guide or reference for developers to follow when using Shadcn UI in future developments.

**Comment by soham901** [comment]
@FrancescoXX

**Comment by FrancescoXX** [comment]
hey @soham901 , we are putting this on hold because I want to create a design team first, we all have different visions

But if you want, you can create a PR to show how it will look like

**Comment by soham901** [comment]
> hey @soham901 , we are putting this on hold because I want to create a design team first, we all have different visions
> 
> But if you want, you can create a PR to show how it will look like

Okay then let's go with the existing solution

**Comment by FrancescoXX** [comment]
closing this for now. IF you want, you can open a discussion about the UI
