### ISSUE TITLE
[FEATURE] Add "People" Section 

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#49]
Add the people section in the project.

For reference, check these files:
https://github.com/FrancescoXX/rustcrab/blob/main/src/components/DevToolsSection.tsx

This for the data (similar structure)
https://github.com/FrancescoXX/rustcrab/blob/main/src/data/tools.ts

and then insert this component into the page.tsk file (similar to what is here at line 39)
https://github.com/FrancescoXX/rustcrab/blob/main/src/app/page.tsx

![image](https://github.com/user-attachments/assets/6848d94f-fd68-45f3-89ae-e2a0655afb97)

for now you can insert dummy content

**Comment by nikkbh** [comment]
Hi @FrancescoXX,
I would love to work on this issue, can you add some examples for this section on how it should look?
Thanks

**Comment by FrancescoXX** [comment]
you can create a component that looks very similar to this one
