### ISSUE TITLE
improve the social media image and title

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#5]
good for when this will be shared on social media, like twitter

**Comment by singh12345akshay** [comment]
Hii @FrancescoXX  can you please elaborate more about this, like what type of improvements you want in social media icons?
Because i want to work on this

**Comment by FrancescoXX** [comment]
no @singh12345akshay , I don't mean the social media icons, but the social media post, like whe yo u link it on twitter

now it looks like this, without any preview

is that clear?

![image](https://github.com/user-attachments/assets/25380dc6-1f1e-4420-8dee-5836faddb30f)

**Comment by singh12345akshay** [comment]
Okay so when we link it with social media then a preview card should be shown, if i'm getting the things clear is that the thing which you want?

**Comment by FrancescoXX** [comment]
ys, I was talking about the preview card. do you want to work on this?

**Comment by singh12345akshay** [comment]
yes, i want

**Comment by felixoder** [comment]
https://github.com/user-attachments/assets/a9cc2403-9294-47ef-bd4d-dac59edd2283

do You want this types social media share button ? @FrancescoXX

**Comment by FrancescoXX** [comment]
@felixoder yes, I want that when I share this as a link, for example on twitter, it shows a preview instead of the bare link

**Comment by felixoder** [comment]
Got it. I can do that!

**Comment by FrancescoXX** [comment]
@felixoder , this has been already assigned to @singh12345akshay

@singh12345akshay , if you want to pass this issue to Felix, let me know

**Comment by FrancescoXX** [comment]
@felixoder do you still want to work on this?

@singh12345akshay do you want to work on this?

**Comment by felixoder** [comment]
@FrancescoXX  you can reassign @singh12345akshay No problem

**Comment by singh12345akshay** [comment]
@felixoder I'm sorry i was busy some where but just give me this weekend i'll complete this thing by this weekend for sure

**Comment by RohittCodes** [comment]
@FrancescoXX can you assign this issue to me?

**Comment by RohittCodes** [comment]
ig adding a few og meta tags will make it work, @FrancescoXX can I work on it?

**Comment by singh12345akshay** [comment]
Hey @FrancescoXX 
That how the preview will be shown on twitter, Facebook or other social media, Did you wanted the same or need any modification

https://github.com/user-attachments/assets/afb5950b-434b-47c7-8c6f-f362846f34c7

**Comment by singh12345akshay** [comment]
@FrancescoXX  as you have merged the Above mentioned branch so now can you please close this issue and please let me know if i can do some more work on this project.

**Comment by FrancescoXX** [comment]
thanks
