### ISSUE TITLE
[FEATURE] Add "Projects" section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#50]
Add the "Where is Rust Used" section in the project.

something like this
https://www.reddit.com/r/rust/comments/umudp6/what_popular_companies_uses_rust/

For reference, check these files:
https://github.com/FrancescoXX/rustcrab/blob/main/src/components/DevToolsSection.tsx

This for the data (similar structure)
https://github.com/FrancescoXX/rustcrab/blob/main/src/data/tools.ts

and then insert this component into the page.tsk file (similar to what is here at line 39)
https://github.com/FrancescoXX/rustcrab/blob/main/src/app/page.tsx

![image](https://github.com/user-attachments/assets/8fc9a07f-4712-4c49-bec2-410e28a0ed93)

**Comment by nikkbh** [comment]
Hi @FrancescoXX,
I would like to contribute on this issue.
Thanks
