### ISSUE TITLE
[FEATURE] Add "Lessons" section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#51]
Add the "Projects" section in the project.

For reference, check these files:
https://github.com/FrancescoXX/rustcrab/blob/main/src/components/DevToolsSection.tsx

This for the data (similar structure)
https://github.com/FrancescoXX/rustcrab/blob/main/src/data/tools.ts

and then insert this component into the page.tsk file (similar to what is here at line 39)
https://github.com/FrancescoXX/rustcrab/blob/main/src/app/page.tsx

for the data, get the yt videos at this playlist
https://www.youtube.com/watch?v=R33h77nrMqc&list=PLPoSdR46FgI412aItyJhj2bF66cudB6Qs

**Comment by DhairyaMajmudar** [comment]
Hi @FrancescoXX this seems to be a cool issue, is there any design specified for creating this section ?

**Comment by FrancescoXX** [comment]
yes @DhairyaMajmudar , please refer to those components

it should look like this 
![image](https://github.com/user-attachments/assets/5406aebe-c6c6-40bc-b4a5-707c151d289e)

**Comment by DhairyaMajmudar** [comment]
> yes @DhairyaMajmudar , please refer to those components
> 
> it should look like this ![image](https://private-user-images.githubusercontent.com/18360871/348477706-5406aebe-c6c6-40bc-b4a5-707c151d289e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODE1NzIsIm5iZiI6MTcyMDg4MTI3MiwicGF0aCI6Ii8xODM2MDg3MS8zNDg0Nzc3MDYtNTQwNmFlYmUtYzZjNi00MGJjLWI0YTUtNzA3YzE1MWQyODllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDE0MzQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NmZjMDM4NTM3ODlmODJjNjdmYmI5MzJiNmZjMmRlY2Y3Yzk4OWU2YjAwY2RmMTU3MDE4YTVkZjgzZTM3M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-MlURTbg9MKGHbDvJL-xoOPemFduuTLsFbaUgXLKyQ4)

Awsm, looking forward to open a draft PR  : D

**Comment by FrancescoXX** [comment]
ok @DhairyaMajmudar , please for this specific component , add a youtube embed section inside the component

**Comment by DhairyaMajmudar** [comment]
@FrancescoXX, I thought of something redesigning things, how's below looking ? Also I am separating type interfaces in `/types` folder to maintain a clean project architecture =) 

![image]( https://github.com/user-attachments/assets/228459db-7a54-4f07-9914-f9cd3c32256f)

**Comment by FrancescoXX** [comment]
we have this now
