### ISSUE TITLE
[FEATURE] Add "Books" section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#52]
Add the "Books" section in the project.

For reference, check these files:
https://github.com/FrancescoXX/rustcrab/blob/main/src/components/DevToolsSection.tsx

This for the data (similar structure)
https://github.com/FrancescoXX/rustcrab/blob/main/src/data/tools.ts

and then insert this component into the page.tsk file (similar to what is here at line 39)
https://github.com/FrancescoXX/rustcrab/blob/main/src/app/page.tsx
![image](https://github.com/user-attachments/assets/695da1bc-9d17-4882-82ff-8fdd30ffe6e5)

**Comment by ayushsarode** [comment]
I would like to work on it @FrancescoXX!

**Comment by FrancescoXX** [comment]
the title is just "Books", you can add something you can find or dummy data, this issue is just to create the component.

you don't have to change the main page, just send the link to reach that component

**Comment by dvpavan-kumar** [comment]
Hi @FrancescoXX  i have create the books section only PR is pending can you assign this task to me.

**Comment by FrancescoXX** [comment]
closed by #60
