### ISSUE TITLE
[DOCS] Update Contributing file

### ISSUE THREAD

**Issue by devvsakib** [FrancescoXX/rustcrab#58]
**Description**

Update the `CONTRIBUTING.md` file to include detailed guidelines for new contributors. The current contributing file lacks proper guidelines, leading to contributors making PRs without assigning issues to themselves and other procedural oversights.

**Expected Behavior**

What should happen?

**Actual Behavior**

What happens instead?

**Screenshots (if applicable)**

Add screenshots or other media to help explain the issue.

**Additional Information**

Add any other context or information about the issue here.

**Comment by devvsakib** [comment]
@FrancescoXX I will working on it, assign this issue to me

**Comment by FrancescoXX** [comment]
Thank you @devvsakib
