### ISSUE TITLE
The Stickyness of Navigation bar

### ISSUE THREAD

**Issue by felixoder** [FrancescoXX/rustcrab#62]
**The Navigation menu is not sticky while scrolling and also it gives a bad user experience sometimes**

Please describe the Feature in detail.

What should happen?

**The Navbar Should be sticky while scrolling and also the background of it should be blur**

https://github.com/user-attachments/assets/806ceb2e-325a-4d3a-b486-a1b80d7d840d

What happens instead?

![image](https://github.com/user-attachments/assets/f57e43f2-9b9d-47e2-bd43-59899af34c2f)

Add screenshots or other media to help explain the issue.

https://github.com/user-attachments/assets/98f96927-f858-4cb1-8ab1-5852e845bf2e

**Additional Information**

One thing please change the background color of your substack its looks creepy lol

**Comment by FrancescoXX** [comment]
thank you. there is an issue related to that, they basically provide a fixed  iframe you can't change

**Comment by FrancescoXX** [comment]
solved by #63

**Comment by felixoder** [comment]
yes I guessed so. Thanks for accepting the PR of this issue ( I had already raised that)

Thanks. It's awesome contributing.
