### ISSUE TITLE
[BUG] Button text in section "Books to Learn Rust" has typo

### ISSUE THREAD

**Issue by visua1hue** [FrancescoXX/rustcrab#64]
**Description**

The button in section "Books to Learn Rust" has typo - it should be "**See More Books**"

**Expected Behavior**

n/a

**Actual Behavior**

n/a

**Screenshots (if applicable)**

<img width="1068" alt="Screenshot 2024-07-13 at 23 00 12" src="https://github.com/user-attachments/assets/e14029b1-75c4-451c-baee-913fa9335713">

**Additional Information**

Fix needs to be applied in https://github.com/FrancescoXX/rustcrab/blob/35628d9690e67748f84a196a232c04a16701c339/src/components/BooksSection.tsx#L43

**Comment by FrancescoXX** [comment]
thanks
