### ISSUE TITLE
change the twitter icon to X

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#7]
![image](https://github.com/FrancescoXX/rustcrab/assets/18360871/79b049be-0598-491a-ad8a-e1a6378eda39)

**Comment by SanketSonawane11** [comment]
Let me do it. It is ready

**Comment by SanketSonawane11** [comment]
I have created a pull request. Please check

**Comment by FrancescoXX** [comment]
done by #15
