### ISSUE TITLE
[OTHER] Navigation is missing in other pages

### ISSUE THREAD

**Issue by devvsakib** [FrancescoXX/rustcrab#70]
**Description**

Navbar is not added to the books/devtools page.

**Expected Behavior**
There should be a navbar or a back button that takes the user to the home page.

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/0560bd39-7663-44e2-a2b6-4eb30b90ab61)

**Comment by FrancescoXX** [comment]
@devvsakib please check it now

https://www.rustcrab.com/

**Comment by FrancescoXX** [comment]
I see the problem here. clicking on the navbar just renders a partial section
![image](https://github.com/user-attachments/assets/33680ae9-ac9e-425d-9469-1ac965967115)

Instead, it should just show directly this: https://www.rustcrab.com/devtools

keeping the top bar and footer.

wdyt @devvsakib

**Comment by devvsakib** [comment]
Yes right.  @FrancescoXX

**Comment by devvsakib** [comment]
assign me, I will fix it

**Comment by FrancescoXX** [comment]
you are rocking it!
