### ISSUE TITLE
[BUG] github star not showing due to API limit 

### ISSUE THREAD

**Issue by devvsakib** [FrancescoXX/rustcrab#71]
**Description**

Due to GitHub API call limit, star count not showing

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/593742ca-0ba5-4d4f-906f-c835208808cd)

**Comment by FrancescoXX** [comment]
I cna still see it. maybe it's related to the specific user and not the project?

**Comment by devvsakib** [comment]
Hmm right, it's exceeded for me. Specific user issue

**Comment by FrancescoXX** [comment]
not sure if we can at least handle the UI so in case we get an error we display something else, wdyt? maybe you are in the position to work on this right now, since you experienced the rate limit

**Comment by devvsakib** [comment]
Now it's showing. GitHub restricted the user for a certain time. I think it's okay because the user is not going to reload the pages, so there will be no API call.

![image](https://github.com/user-attachments/assets/5f4477b4-4e5e-4da3-90c8-b86357ed1579)

**Comment by FrancescoXX** [comment]
ok so we can close this
