### ISSUE TITLE
[OTHER] Devtool page UI improvement

### ISSUE THREAD

**Issue by devvsakib** [FrancescoXX/rustcrab#72]
**Description**

I have added some effects and made minor changes in devtools UI.  Example is given below

Before:
![image](https://github.com/user-attachments/assets/913dbe78-090f-424b-9d70-7374ecaa85f3)

After:
without hover:
![image](https://github.com/user-attachments/assets/7071f783-0489-4775-8268-dc233e42a441)

Hover:
![image](https://github.com/user-attachments/assets/e087b852-e967-45a6-bcab-d5e9df37f897)

**Comment by devvsakib** [comment]
@FrancescoXX What do you think?

**Comment by FrancescoXX** [comment]
@devvsakib it looks very nice do you want to update that? 

The best would be to have a consistent UI

**Comment by devvsakib** [comment]
@FrancescoXX Yeah, I will make a PR ASAP!
