### ISSUE TITLE
[FEATURE] Add Threads link at the bottom

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#76]
Add a link to the Threads account:

https://www.threads.net/@francescociull4

positioning should be on the right of the IG one

![image](https://github.com/user-attachments/assets/ae1d87a1-cec6-45c0-87ef-107db539bf0d)

**Comment by leetebbs** [comment]
Hi @FrancescoXX 
Can you assign this task to me ?
I have created a PR here
https://github.com/FrancescoXX/rustcrab/pull/78

**Comment by FrancescoXX** [comment]
thank you @leetebbs , merged already
