### ISSUE TITLE
[FEATURE] add hover effect on social icons

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/rustcrab#77]
Currently, the social icons at the bottom hav no hover effect

Add a simple one.

It must work both for dark mode ann light mode.

![image](https://github.com/user-attachments/assets/958e09bc-235f-448b-a646-58119da453e7)

**Comment by ramnaresh8** [comment]
@FrancescoXX I would love to work on it, shall I?

**Comment by saivinaygondrala** [comment]
@FrancescoXX either i can work on it

**Comment by FrancescoXX** [comment]
go for it @ramnaresh8

**Comment by ramnaresh8** [comment]
@FrancescoXX thanks for the opportunity, I've submitted the pull request. I would wait for your review. Thanks again :)

**Comment by FrancescoXX** [comment]
closed by #91
