### ISSUE TITLE
[FEATURE] Syntax highlighting for examples 

### ISSUE THREAD

**Issue by hamatoyogi** [FrancescoXX/rustcrab#88]
**Description**

It would be cool if the code blocks in the DSA examples would have syntax highlighting, as well as formatted correctly (aligned to left and not centered)

**Expected Behavior**

code blocks in the DSA examples would have syntax highlighting

**Actual Behavior**

No highlights and text is centered and not left aligned

**Screenshots (if applicable)**

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/22086333-f83a-4c05-85e2-ca9c7599f8e6">

**Comment by felixoder** [comment]
@FrancescoXX  the syntax highlighting can be achieved by a popular lib react-syntax-highlighter and Prism

But I had not found any good for the light mode.

https://github.com/user-attachments/assets/b1a52b44-bedf-4ada-ac9b-b080edc9fa92

@hamatoyogi  are you working with this projcet ?

**Comment by FrancescoXX** [comment]
I am sure we can find smetihng that works both for dark and light mode.

@hamatoyogi let me know if you want to work on it, otherwise I am sure @felixoder can help

**Comment by Thebeast01** [comment]
@FrancescoXX  Can't we use react-syntax-highlighter?

**Comment by Thebeast01** [comment]
I would Like to work on this feature.

**Comment by Thebeast01** [comment]
I tried to work on it locally, I used react-syntax-highlighter
I'm sharing some screen shorts. 
![Screenshot 2024-07-14 200947](https://github.com/user-attachments/assets/bc54d9e4-7ad8-4b19-9275-d670aea9373b)
![Screenshot 2024-07-14 201006](https://github.com/user-attachments/assets/435d5e42-df62-4419-a523-aa75ba32f441)

**Comment by FrancescoXX** [comment]
it already looks nice. align it to the righ and make it look at much as possible as a piece of code.

also, a suggestion might be to put a simple copy icon 📄 at the top right and an x, instead of a copy code and close buttons

**Comment by Thebeast01** [comment]
You mean align code snippet to right?

**Comment by Thebeast01** [comment]
Something like this ? 


![Screenshot 2024-07-14 202334](https://github.com/user-attachments/assets/bd5a66f1-e225-4e97-899d-886cad11e618)

**Comment by Thebeast01** [comment]
@FrancescoXX  Check this out is it good, tried to put an 'x' close to the top right side but it doesn't look good. So I didn't do it if you want, I'll do it.
This is how it looks right now. 
![Screenshot 2024-07-14 204833](https://github.com/user-attachments/assets/c9c6dfa7-dffa-493f-a5fa-782276ed377e)
![Screenshot 2024-07-14 204844](https://github.com/user-attachments/assets/985ee3df-8ae8-4406-8209-3127127dcb8c)
![Screenshot 2024-07-14 204909](https://github.com/user-attachments/assets/c8fd5948-811a-45b2-94b3-6e7086f14bdc)

**Comment by FrancescoXX** [comment]
I think they should be close, you can click copy and the close the window, for the user experience

**Comment by Thebeast01** [comment]
Ok

**Comment by Thebeast01** [comment]
And what about the copy success message Should I leave it there or shift it anywhere else ?

**Comment by Thebeast01** [comment]
@FrancescoXX  Is This okay ? 
![Screenshot 2024-07-14 211721](https://github.com/user-attachments/assets/330d9883-0056-44dd-8401-1c0d412f8428)
![Screenshot 2024-07-14 211802](https://github.com/user-attachments/assets/6e2d8e9e-f3fc-4585-a29f-4fdd517ed163)

**Comment by Thebeast01** [comment]
@FrancescoXX  One more thing I would Like to ask as I can see a new issue has been raised and was assigned to someone, for the button alignment of the same code snippet card, which appears when we click on the show more option of DSA Example page. So, Don't all the cards look like this, if another person works on the same page I might cause a merge conflict.
I am talking about issue #93. 
Do check it out.

**Comment by FrancescoXX** [comment]
yes that works. I merged that because it was an improvmenet anyway, bu I like this solition better

**Comment by Thebeast01** [comment]
So, what should I do, Should I change all the card to this one ? Like all the code snippet card to this one ?

**Comment by Thebeast01** [comment]
@FrancescoXX  I'm Creating a Pull request 
This is what I have changed. This is the find result 
https://github.com/user-attachments/assets/7fb83a64-bf59-4010-9fef-83ffb34bc00c
https://github.com/user-attachments/assets/0615d084-dca2-462f-aeb5-aa0fd53ac6c8

**Comment by Thebeast01** [comment]
![Screenshot 2024-07-14 231258](https://github.com/user-attachments/assets/ffd45d84-9eec-4380-9e34-53c638a053e6)
![Screenshot 2024-07-14 231316](https://github.com/user-attachments/assets/5ebefdd5-d914-4695-9d8a-5c53dd75d3d8)

**Comment by FrancescoXX** [comment]
great

**Comment by hamatoyogi** [comment]
Nice one!
Was planning on helping out, but was in the middle of a workday 😅 
Looks great! 👌🏽
