### ISSUE TITLE
[BUG] Theme was resetting to light mode on refresh 

### ISSUE THREAD

**Issue by saivinaygondrala** [FrancescoXX/rustcrab#90]
**Description**

When i navigate to the Dev Tools > More Dev Tools on refresh it was resetting to light mode even though the dark mode was set.

**Expected Behavior**

It should be dark mode even we refresh in the More Dev Tools page

**Screenshots (if applicable)**

![image](https://github.com/user-attachments/assets/b1943390-ebf5-4359-be6f-3aa856a50157)

**Comment by FrancescoXX** [comment]
I think it should be set in localstorage, if this is what you mean.

Do you want to work on it?

**Comment by saivinaygondrala** [comment]
Sure ill work on it.

**Comment by shibu69** [comment]
Is this issue solved now??

**Comment by saivinaygondrala** [comment]
Not yet

**Comment by shibu69** [comment]
it is solved now because i can't see the issue you mentioned on the site
