### ISSUE TITLE
[BUG] On Hover showing Scrollbars

### ISSUE THREAD

**Issue by saivinaygondrala** [FrancescoXX/rustcrab#92]
**Description**

In the More Dev Tools page when hovering on the right most tool cards it is showing the right and bottom scroll bars. 

**Expected Behavior**

It could be better if they can be able to hide. 

**Screenshots (if applicable)**

**On Hover:**

![image](https://github.com/user-attachments/assets/76d0ce8e-0c32-40f3-9808-7fd4dda57d86)

**Without hovering**
![image](https://github.com/user-attachments/assets/31ac8097-1d02-491a-9f9c-e747b9a1371a)

**Additional Information**

It can be fixed if the overflow was hidden

**Comment by FrancescoXX** [comment]
nice go for it

**Comment by FrancescoXX** [comment]
#97
