### ISSUE TITLE
[BUG] The Code preview tab the buttons were inconsistent

### ISSUE THREAD

**Issue by saivinaygondrala** [FrancescoXX/rustcrab#93]
**Description**

On navigating to the DSA Examples page on clicking on View Code the buttons were First one is Copy Code and next one is Close. On navigating to Show more page in DSA Examples There on clicking on view code the buttons order was Close and Copy Code.

**Expected Behavior**

The buttons should be in the same order. 

**Screenshots (if applicable)**

**On the DSA Example page:**
![image](https://github.com/user-attachments/assets/adac615f-10fc-4dfc-959b-8c9b427aa673)

**On Show More:**
![image](https://github.com/user-attachments/assets/12d3c499-0752-45ba-ae2d-0968fa45a199)

**Comment by FrancescoXX** [comment]
nice catch
